name: Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [nightly, stable]
    steps:

      - name: Starting Gremlin Servers
        run: |
          docker-compose -f ./docker-compose/docker-compose.yaml up -d 
        
      - uses: actions/checkout@v2
      - name: Install latest ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Run cargo test with tokio
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path gremlin-client/Cargo.toml  --features=tokio-runtime
      - name: Run cargo test with async-std
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path gremlin-client/Cargo.toml --features=async-std-runtime
